# Generated by Django 3.2.7 on 2021-10-16 22:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localidades_brasileiras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificacao', models.DateTimeField(auto_now=True, verbose_name='Modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('classe', models.CharField(max_length=50, verbose_name='Classe')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Salário')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificacao', models.DateTimeField(auto_now=True, verbose_name='Modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificacao', models.DateTimeField(auto_now=True, verbose_name='Modificação')),
                ('is_principal', models.BooleanField(default=False, verbose_name='É o endereço principal')),
                ('logradouro', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('complemento', models.CharField(blank=True, max_length=50, verbose_name='Complemento')),
                ('cep', models.CharField(max_length=20, verbose_name='CEP')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'ordering': ['perfil'],
            },
        ),
        migrations.CreateModel(
            name='OutroEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificacao', models.DateTimeField(auto_now=True, verbose_name='Modificação')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Outro e-mail',
                'verbose_name_plural': 'Outros e-mails',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificacao', models.DateTimeField(auto_now=True, verbose_name='Modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=200, verbose_name='Sobrenome')),
                ('cpf', models.CharField(blank=True, max_length=40, unique=True, verbose_name='CPF')),
                ('contrato_identificador', models.CharField(max_length=200, verbose_name='Identificador do Contrato')),
                ('data_admissao', models.DateField(verbose_name='Data de admissão')),
                ('data_demissao', models.DateField(null=True, verbose_name='Data de demissão')),
                ('dados_bancarios_banco', models.CharField(blank=True, max_length=200, verbose_name='Dados bancários - Banco')),
                ('dados_bancarios_agencia', models.CharField(blank=True, max_length=200, verbose_name='Dados bancários - Agência')),
                ('dados_bancarios_conta', models.CharField(blank=True, max_length=200, verbose_name='Dados bancários - Conta')),
                ('cargos', models.ManyToManyField(blank=True, related_name='perfis', to='perfis.Cargo')),
                ('departamentos', models.ManyToManyField(blank=True, related_name='perfis', to='perfis.Departamento')),
                ('municipios_onde_trabalha', models.ManyToManyField(blank=True, related_name='perfis', to='localidades_brasileiras.Municipio')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificacao', models.DateTimeField(auto_now=True, verbose_name='Modificação')),
                ('numero', models.CharField(max_length=25, verbose_name='Telefone')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to='perfis.perfil')),
            ],
            options={
                'verbose_name': 'Telefone',
                'verbose_name_plural': 'Telefones',
            },
        ),
    ]
