# Generated by Django 3.2.7 on 2021-09-28 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0003_auto_20210923_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='diretor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='diretor_em', to='perfis.perfil', verbose_name='Diretor do departamento'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='diretor_substituto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='diretor_substituto_em', to='perfis.perfil', verbose_name='Diretor substituto do departamento'),
        ),
    ]
