# Generated by Django 3.2.7 on 2021-09-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localidades_brasileiras', '0003_alter_municipio_nome'),
        ('perfis', '0004_auto_20210928_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cargos',
            field=models.ManyToManyField(blank=True, related_name='perfis', to='perfis.Cargo'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='departamentos',
            field=models.ManyToManyField(blank=True, related_name='perfis', to='perfis.Departamento'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='municipios_onde_trabalha',
            field=models.ManyToManyField(blank=True, related_name='perfis', to='localidades_brasileiras.Municipio'),
        ),
    ]
