# Generated by Django 3.2.7 on 2021-10-02 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perfis', '0006_alter_departamento_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='usuario_modificacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='usuarios.customusuario', verbose_name='Usuário da modificação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departamento',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='usuario_modificacao',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='usuarios.customusuario', verbose_name='Usuário da modificação'),
            preserve_default=False,
        ),
    ]
