# Generated by Django 3.2.7 on 2021-09-13 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificacao', models.DateTimeField(auto_now=True, verbose_name='Modificação')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome do Município')),
                ('cod_ibge', models.CharField(max_length=50, unique=True, verbose_name='Código do IBGE')),
                ('latitude', models.CharField(max_length=50, verbose_name='Latitude')),
                ('longitude', models.CharField(max_length=50, verbose_name='Longitude')),
                ('ddd', models.PositiveSmallIntegerField(verbose_name='DDD')),
                ('fuso_horario', models.CharField(max_length=50, verbose_name='Fuso horário')),
                ('cod_siafi', models.CharField(max_length=20, verbose_name='Código do SIAFI')),
            ],
            options={
                'verbose_name': 'Município',
                'verbose_name_plural': 'Municípios',
            },
        ),
        migrations.CreateModel(
            name='UnidadeFederativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificacao', models.DateTimeField(auto_now=True, verbose_name='Modificação')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
                ('sigla', models.CharField(max_length=10, unique=True, verbose_name='Sigla')),
                ('cod_ibge', models.CharField(max_length=50, unique=True, verbose_name='Código do IBGE')),
                ('latitude', models.CharField(max_length=50, verbose_name='Latitude')),
                ('longitude', models.CharField(max_length=50, verbose_name='Longitude')),
                ('capital', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='capital_de', to='localidades_brasileiras.municipio')),
            ],
            options={
                'verbose_name': 'Unidade Federativa',
                'verbose_name_plural': 'Unidades Federativas',
            },
        ),
        migrations.AddField(
            model_name='municipio',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='localidades_brasileiras.unidadefederativa'),
        ),
    ]
