# Generated by Django 3.2.7 on 2021-09-13 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localidades_brasileiras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadefederativa',
            name='capital',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='capital_de', to='localidades_brasileiras.municipio'),
        ),
    ]
