# Generated by Django 3.2 on 2021-05-23 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('municipios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MunicipioOndeTrabalha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificacao', models.DateTimeField(auto_now=True, verbose_name='Modificação')),
            ],
            options={
                'verbose_name': 'Município onde trabalha',
                'verbose_name_plural': 'Municípios onde trabalha',
            },
        ),
        migrations.CreateModel(
            name='OutroEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificacao', models.DateTimeField(auto_now=True, verbose_name='Modificação')),
                ('email', models.EmailField(help_text='Informe o e-mail da Promotoria e outros que desejar.', max_length=254, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Outro e-mail',
                'verbose_name_plural': 'Outros e-mails',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificacao', models.DateTimeField(auto_now=True, verbose_name='Modificação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=200, verbose_name='Sobrenome')),
                ('municipios_onde_trabalha', models.ManyToManyField(help_text='Informe também os TERMOS da comarca.', through='perfis.MunicipioOndeTrabalha', to='municipios.Municipio')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificacao', models.DateTimeField(auto_now=True, verbose_name='Modificação')),
                ('numero', models.CharField(help_text='Informe o telefone da Promotoria e outros que desejar.', max_length=20, verbose_name='Telefone')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to='perfis.perfil')),
            ],
            options={
                'verbose_name': 'Telefone',
                'verbose_name_plural': 'Telefones',
            },
        ),
    ]
