# Generated by Django 3.2 on 2021-05-23 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('municipios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perfil',
            name='usuario_modificacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuário da modificação'),
        ),
        migrations.AddField(
            model_name='outroemail',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outros_emails', to='perfis.perfil'),
        ),
        migrations.AddField(
            model_name='municipioondetrabalha',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perfis', to='municipios.municipio', verbose_name='Município onde trabalha'),
        ),
        migrations.AddField(
            model_name='municipioondetrabalha',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfis.perfil'),
        ),
    ]
