# Generated by Django 3.2 on 2021-05-23 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Macrorregiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificacao', models.DateTimeField(auto_now=True, verbose_name='Modificação')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome da Macrorregião')),
            ],
            options={
                'verbose_name': 'Macrorregião',
                'verbose_name_plural': 'Macrorregiões',
            },
        ),
        migrations.CreateModel(
            name='Mesorregiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificacao', models.DateTimeField(auto_now=True, verbose_name='Modificação')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome da Mesorregião')),
                ('macrorregiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesorregioes', to='municipios.macrorregiao')),
            ],
            options={
                'verbose_name': 'Mesorregião',
                'verbose_name_plural': 'Mesorregiões',
            },
        ),
        migrations.CreateModel(
            name='Microrregiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificacao', models.DateTimeField(auto_now=True, verbose_name='Modificação')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome da Microrregião')),
                ('mesorregiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microrregioes', to='municipios.mesorregiao')),
            ],
            options={
                'verbose_name': 'Microrregião',
                'verbose_name_plural': 'Microrregiões',
            },
        ),
        migrations.CreateModel(
            name='RegiaoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificacao', models.DateTimeField(auto_now=True, verbose_name='Modificação')),
                ('numero', models.PositiveIntegerField(unique=True, verbose_name='Número da Região de Saúde')),
            ],
            options={
                'verbose_name': 'Região de Saúde',
                'verbose_name_plural': 'Regiões de Saúde',
            },
        ),
        migrations.CreateModel(
            name='UnidadeFederativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificacao', models.DateTimeField(auto_now=True, verbose_name='Modificação')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome da Unidade Federativa')),
                ('sigla', models.CharField(max_length=10, unique=True, verbose_name='Sigla da Unidade Federativa')),
                ('cod_ibge', models.CharField(max_length=200, unique=True, verbose_name='Código do IBGE')),
            ],
            options={
                'verbose_name': 'Unidade Federativa',
                'verbose_name_plural': 'Unidades Federativas',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criação')),
                ('modificacao', models.DateTimeField(auto_now=True, verbose_name='Modificação')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome do Município')),
                ('cod_ibge', models.CharField(max_length=200, unique=True, verbose_name='Código do IBGE')),
                ('microrregiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='municipios.microrregiao')),
                ('regiao_saude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='municipios.regiaosaude')),
                ('uf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='municipios.unidadefederativa')),
            ],
            options={
                'verbose_name': 'Município',
                'verbose_name_plural': 'Municípios',
            },
        ),
    ]
